[package]
name = "interest-calc"
version = "0.1.0"
authors = ["Troy B <troy.bevis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
rusty-money = "0.3.4"